# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12b2067e61c31821cb5e80952cd3b853f17998970eda6af1289d6a581294f652cede2a89cb37a2d0841ffa8d9a696241f2cc471637b0c8a24a6ba839b905c79e

test:
  secret_key_base: b3f3c58de5bb277fefd01ce2654f3e3201c6773dffcc09f812877ecc275c8b7a964be477763067a60a188ebcd0c703ff0d42b5eca72a11f527badd83e5ca0d66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
